git:
  commit:
    signOff: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  openLink: >
    if [[ "$TERM" =~ ^(screen|tmux) ]]; then
      printf "\033Ptmux;\033\033]52;c;$(printf {{link}} | base64 -w 0)\a\033\\" > /dev/tty
    else
      printf "\033]52;c;$(printf {{link}} | base64 -w 0)\a" > /dev/tty
    fi
  copyToClipboardCmd: >
    if [[ "$TERM" =~ ^(screen|tmux) ]]; then
      printf "\033Ptmux;\033\033]52;c;$(printf {{text}} | base64 -w 0)\a\033\\" > /dev/tty
    else
      printf "\033]52;c;$(printf {{text}} | base64 -w 0)\a" > /dev/tty
    fi
gui:
  nerdFontsVersion: "3"
  switchTabsWithPanelJumpKeys: true
